FROM grafana/grafana:10.0.0

USER root

RUN wget https://apps.afrikpay.com/assets/icons/icon-512x512.png && mv icon-512x512.png /usr/share/grafana/public/img/grafana_icon.svg
RUN wget https://apps.afrikpay.com/assets/icons/icon-512x512.png && mv icon-512x512.png /usr/share/grafana/public/img/fav32.png

USER grafana